name: Run PHPCS, PHPLint and Psalm

on: [pull_request, push]

jobs:
  linting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        task: [phpcs, phplint, psalm]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Show version info
        run: ./vendor/bin/${{ matrix.task }} --version

      - name: Run ${{ matrix.task | toLowerCase() }}
        run: composer ${{ matrix.task }}
